#!/usr/bin/env bash
#
# Initialize DTLR Governance in a repository
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/dtlr/governance-core/main/automation/init-governance.sh | bash
#   # OR
#   ./init-governance.sh --type iac --name my-repo
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_TYPE=""
REPO_NAME=""
INTERACTIVE=true

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --type)
      REPO_TYPE="$2"
      INTERACTIVE=false
      shift 2
      ;;
    --name)
      REPO_NAME="$2"
      shift 2
      ;;
    --non-interactive)
      INTERACTIVE=false
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  DTLR Governance Initialization${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if in git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo -e "${RED}❌ Not a git repository${NC}"
  echo "Run: git init"
  exit 1
fi

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

# Get repo name from directory if not provided
if [[ -z "$REPO_NAME" ]]; then
  REPO_NAME=$(basename "$REPO_ROOT")
fi

# Interactive mode
if [[ "$INTERACTIVE" == "true" ]]; then
  echo "Repository: $REPO_NAME"
  echo ""
  echo "Select repository type:"
  echo "  1) Multi-cloud IaC (Terraform/OpenTofu with multiple providers)"
  echo "  2) Single-cloud IaC (Terraform/OpenTofu single provider)"
  echo "  3) Application (web app, API, service)"
  echo "  4) Library (reusable code package)"
  echo "  5) Data Pipeline (ETL, analytics)"
  echo ""
  read -p "Selection [1-5]: " selection

  case $selection in
    1) REPO_TYPE="multi-cloud-iac" ;;
    2) REPO_TYPE="single-cloud-iac" ;;
    3) REPO_TYPE="application" ;;
    4) REPO_TYPE="library" ;;
    5) REPO_TYPE="pipeline" ;;
    *) echo "Invalid selection"; exit 1 ;;
  esac
fi

echo ""
echo -e "${GREEN}Repository: $REPO_NAME${NC}"
echo -e "${GREEN}Type: $REPO_TYPE${NC}"
echo ""

# Determine which submodules to add
SUBMODULES=("core")

case $REPO_TYPE in
  multi-cloud-iac|single-cloud-iac)
    SUBMODULES+=("iac" "terraform")
    ;;
  application)
    SUBMODULES+=("app")
    ;;
  library)
    SUBMODULES+=("library")
    ;;
  pipeline)
    SUBMODULES+=("pipeline")
    ;;
esac

echo -e "${BLUE}📦 Adding governance submodules...${NC}"
mkdir -p .governance

for module in "${SUBMODULES[@]}"; do
  if [[ -d ".governance/$module" ]]; then
    echo -e "${YELLOW}⚠️  .governance/$module already exists, skipping${NC}"
  else
    echo "  Adding governance-$module..."
    git submodule add "https://github.com/dtlr/governance-$module.git" ".governance/$module"
  fi
done

echo ""
echo -e "${BLUE}📝 Creating governance manifest...${NC}"

# Detect primary language
PRIMARY_LANG="unknown"
if [[ -f "package.json" ]]; then
  PRIMARY_LANG="javascript"
elif [[ -f "go.mod" ]]; then
  PRIMARY_LANG="go"
elif [[ -f "Cargo.toml" ]]; then
  PRIMARY_LANG="rust"
elif [[ -f "pyproject.toml" ]] || [[ -f "setup.py" ]]; then
  PRIMARY_LANG="python"
elif [[ -f "main.tf" ]] || [[ -f "*.tf" ]]; then
  PRIMARY_LANG="terraform"
fi

# Create manifest
mkdir -p .governance-local
cat > .governance-local/overrides.yaml <<EOF
# DTLR Governance Manifest
# Auto-generated by init-governance.sh

governance:
  versions:
    core: "v1.0.0"
$(if [[ " ${SUBMODULES[*]} " =~ " iac " ]]; then echo "    iac: \"v1.0.0\""; fi)
$(if [[ " ${SUBMODULES[*]} " =~ " terraform " ]]; then echo "    terraform: \"v1.0.0\""; fi)
$(if [[ " ${SUBMODULES[*]} " =~ " app " ]]; then echo "    app: \"v1.0.0\""; fi)

repository:
  name: "$REPO_NAME"
  type: "$REPO_TYPE"
  description: "TODO: Add repository description"
  primary_language: "$PRIMARY_LANG"

# Template variables for generating CLAUDE.md
template_vars:
  repo_name: "$REPO_NAME"
  # TODO: Add repo-specific variables

# Compliance flags
compliance:
  enforce_saved_plans: $(if [[ "$REPO_TYPE" =~ iac ]]; then echo "true"; else echo "false"; fi)
  enforce_validation: true
  require_pr_reviews: true
  require_issue_tracking: false

# Repo-specific rules (optional)
custom_rules: []
EOF

echo "  Created .governance-local/overrides.yaml"
echo ""

echo -e "${BLUE}🔧 Creating governance scripts...${NC}"
mkdir -p scripts/governance

# Copy scripts from governance-core
if [[ -d ".governance/ai/core/automation/scripts" ]]; then
  cp .governance/ai/core/automation/scripts/* scripts/governance/ 2>/dev/null || true
  chmod +x scripts/governance/*.sh
  echo "  Created scripts/governance/ directory"
fi

echo ""
echo -e "${BLUE}📋 Generating CLAUDE.md...${NC}"

# Run template generation
if [[ -f "scripts/governance/template.sh" ]]; then
  ./scripts/governance/template.sh
  echo "  Generated CLAUDE.md from templates"
else
  echo -e "${YELLOW}⚠️  Template script not found, skipping generation${NC}"
  echo "  You'll need to create CLAUDE.md manually or run: ./scripts/governance/template.sh"
fi

echo ""
echo -e "${BLUE}🔍 Validating setup...${NC}"
if [[ -f "scripts/governance/validate.sh" ]]; then
  if ./scripts/governance/validate.sh --quiet; then
    echo -e "${GREEN}✅ Validation passed${NC}"
  else
    echo -e "${YELLOW}⚠️  Some validation issues found${NC}"
    echo "  Run: ./scripts/governance/validate.sh for details"
  fi
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Governance initialization complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Next steps:"
echo "  1. Review .governance-local/overrides.yaml and update as needed"
echo "  2. Review generated CLAUDE.md"
echo "  3. Stage changes: git add .governance* CLAUDE.md scripts/"
echo "  4. Commit: git commit -m 'chore: Initialize DTLR governance'"
echo ""
echo "Maintenance:"
echo "  - Update governance: ./scripts/governance/sync.sh <version>"
echo "  - Validate compliance: ./scripts/governance/validate.sh"
echo "  - Regenerate CLAUDE.md: ./scripts/governance/template.sh"
echo ""
