#!/usr/bin/env bash
set -euo pipefail

# plan-feature.sh - Transform user request into executable implementation plan
#
# Features:
# - Prioritizes tasks (P0-P3) with reasoning
# - Allows user to select which tasks to execute
# - Defers undone work to GitHub issues

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

DRY_RUN=false
INTERACTIVE=false
CLEANUP=false
DEFER_ISSUE=false
REQUEST=""
EXECUTE_SCOPE="review"  # review, all, p0-p1, p0, custom
SESSION_ID=$(date +%Y%m%d-%H%M%S)
START_TIME=$(date +%s)

usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS]

Transform a user request into an executable implementation plan.

Options:
    --request "text"    The feature/change request
    --execute SCOPE     Execution scope: all, p0-p1, p0, custom:01,02,03
    --defer-issue       Create GitHub issue for deferred tasks
    --dry-run           Show prompts without executing
    --interactive       Run prompts interactively
    --cleanup <dir>     Clean up ephemeral files after deployment
    -h, --help          Show this help message

Execution Scopes:
    review    Show breakdown and ask for approval (default)
    all       Execute all tasks
    p0-p1     Execute P0 (Critical) and P1 (High) only, defer rest
    p0        Execute P0 (Critical) only, defer rest
    custom:X  Execute specific tasks by ID (e.g., custom:01,02,05)

Examples:
    # Plan and review before execution
    $(basename "$0") --request "Add Redis caching"
    
    # Plan and execute only critical tasks, defer rest to GitHub
    $(basename "$0") --request "Add Redis" --execute p0-p1 --defer-issue
    
    # Execute specific tasks
    $(basename "$0") --request "Add Redis" --execute custom:01,02,03
EOF
    exit 0
}

# Create GitHub issue for deferred work
create_defer_issue() {
    local feature_dir="$1"
    local deferred_tasks="$2"
    local feature_name=$(basename "$feature_dir")
    
    echo -e "${BLUE}Creating GitHub issue for deferred work...${NC}"
    
    # Build issue body
    local issue_body=$(cat << ISSUE
## Deferred Work from Feature Planning

**Feature**: $feature_name
**Session**: $SESSION_ID
**Deferred**: $(date -Iseconds)

### Original Request
$(cat "$REPO_ROOT/.ai/_scratch/user-request.md" 2>/dev/null || echo "N/A")

### Deferred Tasks

$deferred_tasks

### Context Files

The following files contain context for implementing these tasks:

- \`$feature_dir/PDR.md\` - Technical design record
- \`$feature_dir/FEATURE.md\` - Feature specification
- \`$feature_dir/research/\` - Research artifacts
- \`$feature_dir/validation.md\` - Risk analysis

### Acceptance Criteria

From FEATURE.md:
$(grep -A20 "### Should Have\|### Nice to Have" "$feature_dir/FEATURE.md" 2>/dev/null | head -30 || echo "See FEATURE.md")

### To Resume

\`\`\`bash
# Review the deferred tasks
cat $feature_dir/REVIEW.md

# Generate prompts for deferred tasks
# (manually select tasks from tasks.json)
\`\`\`

---
*Auto-generated by plan-feature.sh*
ISSUE
)
    
    # Check if gh CLI is available
    if command -v gh &> /dev/null; then
        # Get repo info
        local repo_owner=$(gh repo view --json owner -q '.owner.login' 2>/dev/null || echo "")
        local repo_name=$(gh repo view --json name -q '.name' 2>/dev/null || echo "")
        
        if [[ -n "$repo_owner" ]] && [[ -n "$repo_name" ]]; then
            # Create issue
            local issue_url=$(gh issue create \
                --title "🔮 Deferred: $feature_name" \
                --body "$issue_body" \
                --label "ai-deferred,backlog" \
                2>/dev/null || echo "")
            
            if [[ -n "$issue_url" ]]; then
                echo -e "${GREEN}✓ Created GitHub issue: $issue_url${NC}"
                
                # Record in feature directory
                echo "$issue_url" > "$feature_dir/DEFERRED_ISSUE.txt"
                
                # Append to manifest
                cat >> "$feature_dir/MANIFEST.md" << EOF

## Deferred to GitHub

**Issue**: $issue_url
**Created**: $(date -Iseconds)
**Tasks deferred**: $(echo "$deferred_tasks" | grep -c "Task" || echo "?")
EOF
                return 0
            fi
        fi
    fi
    
    # Fallback: create local file
    echo -e "${YELLOW}GitHub CLI not available or not authenticated.${NC}"
    echo -e "${YELLOW}Creating local deferred work file instead.${NC}"
    
    echo "$issue_body" > "$feature_dir/DEFERRED_WORK.md"
    echo -e "${GREEN}✓ Created: $feature_dir/DEFERRED_WORK.md${NC}"
    echo ""
    echo "To create GitHub issue manually:"
    echo "  gh issue create --title '🔮 Deferred: $feature_name' --body-file $feature_dir/DEFERRED_WORK.md --label ai-deferred,backlog"
}

# Initialize manifest
init_manifest() {
    local feature_dir="$1"
    local manifest="$feature_dir/MANIFEST.md"
    
    cat > "$manifest" << EOF
# File Manifest

**Session**: $SESSION_ID
**Created**: $(date -Iseconds)

## File Categories

| Category | Keep | Description |
|----------|------|-------------|
| DOCS | ✅ | Documentation (FEATURE.md, PDR.md) |
| RESEARCH | ❌ | Research artifacts |
| PROMPTS | ❌ | Execution prompts |
| LOGS | ❌ | Execution logs |

## Files Created

| File | Category | Keep |
|------|----------|------|
EOF
}

track_file() {
    local feature_dir="$1"
    local file_path="$2"
    local category="$3"
    local manifest="$feature_dir/MANIFEST.md"
    local keep="❌"
    [[ "$category" == "DOCS" ]] && keep="✅"
    echo "| \`$file_path\` | $category | $keep |" >> "$manifest"
}

cleanup_feature() {
    local feature_dir="$1"
    # ... (same as before)
    echo "Cleanup: $feature_dir"
}

log_to_ledger() {
    local status="$1"
    local details="$2"
    local ledger_file="$REPO_ROOT/.ai/ledger/LEDGER.md"
    mkdir -p "$(dirname "$ledger_file")"
    [[ ! -f "$ledger_file" ]] && echo "# Operations Ledger" > "$ledger_file"
    
    cat >> "$ledger_file" << ENTRY

---
### $(date -Iseconds) - Feature Planning ($status)
**Session**: $SESSION_ID
$details
ENTRY
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --request) REQUEST="$2"; shift 2 ;;
        --execute) EXECUTE_SCOPE="$2"; shift 2 ;;
        --defer-issue) DEFER_ISSUE=true; shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        --interactive) INTERACTIVE=true; shift ;;
        --cleanup) cleanup_feature "$2"; exit 0 ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

# Find governance
GOVERNANCE_PATH=""
[[ -d "$REPO_ROOT/.governance/ai" ]] && GOVERNANCE_PATH="$REPO_ROOT/.governance/ai"
[[ -z "$GOVERNANCE_PATH" ]] && { echo -e "${RED}Error: Governance submodule not found${NC}"; exit 1; }

BUNDLE_PATH="$GOVERNANCE_PATH/core/templates/golden-image/.ai/bundles/feature-planning-v1"
[[ ! -d "$BUNDLE_PATH" ]] && { echo -e "${RED}Error: Bundle not found${NC}"; exit 1; }

# Setup
mkdir -p "$REPO_ROOT/.ai/_scratch"
mkdir -p "$REPO_ROOT/.ai/ledger"

# Handle request
[[ -n "$REQUEST" ]] && echo "$REQUEST" > "$REPO_ROOT/.ai/_scratch/user-request.md"
[[ ! -f "$REPO_ROOT/.ai/_scratch/user-request.md" ]] && {
    echo -e "${YELLOW}Enter your request (Ctrl+D when done):${NC}"
    cat > "$REPO_ROOT/.ai/_scratch/user-request.md"
}

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║           Feature Planning Pipeline                          ║${NC}"
echo -e "${BLUE}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${BLUE}║  Session: $SESSION_ID                              ║${NC}"
echo -e "${BLUE}║  Scope:   $EXECUTE_SCOPE                                       ${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

[[ "$DRY_RUN" == true ]] && { echo "DRY RUN"; exit 0; }
command -v claude &> /dev/null || { echo -e "${RED}Error: claude CLI not found${NC}"; exit 1; }

# Create feature directory
FEATURE_DIR="$REPO_ROOT/.ai/_scratch/feature-$SESSION_ID"
mkdir -p "$FEATURE_DIR/research" "$FEATURE_DIR/prompts"
init_manifest "$FEATURE_DIR"

# Phase 1: Research and Planning (prompts 00-05)
echo -e "${MAGENTA}═══ PHASE 1: Research & Planning ═══${NC}"

PLANNING_PROMPTS=(00 01 02 03 04 05)
for num in "${PLANNING_PROMPTS[@]}"; do
    prompt=$(find "$BUNDLE_PATH/prompts" -name "${num}_*.md" | head -1)
    [[ -z "$prompt" ]] && continue
    
    PROMPT_NAME=$(basename "$prompt" .md)
    echo -e "${BLUE}→ $PROMPT_NAME${NC}"
    
    LOG_FILE="$FEATURE_DIR/${PROMPT_NAME}.log"
    if claude -p "$(cat "$prompt")" --allowedTools Edit,Write,Bash 2>&1 | tee "$LOG_FILE"; then
        track_file "$FEATURE_DIR" "$LOG_FILE" "LOGS"
        echo -e "${GREEN}✓${NC}"
    else
        echo -e "${RED}✗ Failed${NC}"
        exit 1
    fi
done

# Phase 2: Decomposition and Prioritization (prompts 06, 06b)
echo ""
echo -e "${MAGENTA}═══ PHASE 2: Task Decomposition ═══${NC}"

for num in 06 06b; do
    prompt=$(find "$BUNDLE_PATH/prompts" -name "${num}*.md" | head -1)
    [[ -z "$prompt" ]] && continue
    
    PROMPT_NAME=$(basename "$prompt" .md)
    echo -e "${BLUE}→ $PROMPT_NAME${NC}"
    
    LOG_FILE="$FEATURE_DIR/${PROMPT_NAME}.log"
    claude -p "$(cat "$prompt")" --allowedTools Edit,Write,Bash 2>&1 | tee "$LOG_FILE"
    track_file "$FEATURE_DIR" "$LOG_FILE" "LOGS"
done

# Show review
echo ""
echo -e "${MAGENTA}═══ TASK REVIEW ═══${NC}"
if [[ -f "$FEATURE_DIR/REVIEW.md" ]]; then
    cat "$FEATURE_DIR/REVIEW.md"
else
    echo -e "${YELLOW}REVIEW.md not generated - showing tasks.json${NC}"
    cat "$FEATURE_DIR/tasks.json" 2>/dev/null || echo "No tasks found"
fi

# User decision point
if [[ "$EXECUTE_SCOPE" == "review" ]]; then
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║  DECISION REQUIRED                                           ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Options:"
    echo "  ${GREEN}all${NC}      - Execute all tasks"
    echo "  ${YELLOW}p0-p1${NC}    - Execute P0+P1, defer P2+P3 to GitHub issue"
    echo "  ${YELLOW}p0${NC}       - Execute P0 only, defer rest to GitHub issue"
    echo "  ${RED}none${NC}     - Defer everything to GitHub issue"
    echo "  ${BLUE}custom${NC}   - Specify task IDs (e.g., 01,02,05)"
    echo ""
    read -p "Execute scope [all/p0-p1/p0/none/custom]: " EXECUTE_SCOPE
    EXECUTE_SCOPE=${EXECUTE_SCOPE:-all}
fi

# Determine which tasks to execute vs defer
TASKS_TO_EXECUTE=""
TASKS_TO_DEFER=""

case "$EXECUTE_SCOPE" in
    all)
        TASKS_TO_EXECUTE="all"
        ;;
    p0-p1)
        TASKS_TO_EXECUTE=$(jq -r '.tasks[] | select(.priority == "P0" or .priority == "P1") | .id' "$FEATURE_DIR/tasks.json" 2>/dev/null | tr '\n' ',' | sed 's/,$//')
        TASKS_TO_DEFER=$(jq -r '.tasks[] | select(.priority == "P2" or .priority == "P3") | "- Task \(.id): \(.name) [\(.priority)] - \(.priority_reason)"' "$FEATURE_DIR/tasks.json" 2>/dev/null)
        ;;
    p0)
        TASKS_TO_EXECUTE=$(jq -r '.tasks[] | select(.priority == "P0") | .id' "$FEATURE_DIR/tasks.json" 2>/dev/null | tr '\n' ',' | sed 's/,$//')
        TASKS_TO_DEFER=$(jq -r '.tasks[] | select(.priority != "P0") | "- Task \(.id): \(.name) [\(.priority)] - \(.priority_reason)"' "$FEATURE_DIR/tasks.json" 2>/dev/null)
        ;;
    none)
        TASKS_TO_EXECUTE=""
        TASKS_TO_DEFER=$(jq -r '.tasks[] | "- Task \(.id): \(.name) [\(.priority)] - \(.priority_reason)"' "$FEATURE_DIR/tasks.json" 2>/dev/null)
        ;;
    custom:*)
        TASKS_TO_EXECUTE="${EXECUTE_SCOPE#custom:}"
        # Defer everything not in the custom list
        ;;
esac

# Create GitHub issue for deferred work
if [[ -n "$TASKS_TO_DEFER" ]] && [[ "$DEFER_ISSUE" == true || "$EXECUTE_SCOPE" != "all" ]]; then
    echo ""
    echo -e "${YELLOW}═══ DEFERRED WORK ═══${NC}"
    echo "$TASKS_TO_DEFER"
    echo ""
    
    if [[ "$DEFER_ISSUE" == true ]] || [[ "$INTERACTIVE" == true ]]; then
        read -p "Create GitHub issue for deferred tasks? [Y/n]: " create_issue
        create_issue=${create_issue:-Y}
        if [[ "$create_issue" =~ ^[Yy] ]]; then
            create_defer_issue "$FEATURE_DIR" "$TASKS_TO_DEFER"
        fi
    fi
fi

# Phase 3: Generate and execute prompts for selected tasks
if [[ -n "$TASKS_TO_EXECUTE" ]] && [[ "$TASKS_TO_EXECUTE" != "" ]]; then
    echo ""
    echo -e "${MAGENTA}═══ PHASE 3: Execution ═══${NC}"
    echo -e "Executing tasks: ${GREEN}$TASKS_TO_EXECUTE${NC}"
    
    # Generate prompts (prompt 07)
    prompt=$(find "$BUNDLE_PATH/prompts" -name "07*.md" | head -1)
    if [[ -n "$prompt" ]]; then
        echo -e "${BLUE}→ Generating execution prompts${NC}"
        claude -p "$(cat "$prompt")" --allowedTools Edit,Write,Bash
    fi
    
    # Execute generated prompts
    if [[ -d "$FEATURE_DIR/prompts" ]]; then
        for task_prompt in "$FEATURE_DIR/prompts/"[0-9]*.md; do
            [[ ! -f "$task_prompt" ]] && continue
            TASK_ID=$(basename "$task_prompt" | grep -oE '^[0-9]+')
            
            # Check if this task should be executed
            if [[ "$TASKS_TO_EXECUTE" == "all" ]] || [[ ",$TASKS_TO_EXECUTE," == *",$TASK_ID,"* ]]; then
                echo -e "${BLUE}→ Executing task $TASK_ID${NC}"
                claude -p "$(cat "$task_prompt")" --allowedTools Edit,Write,Bash
                echo -e "${GREEN}✓ Task $TASK_ID complete${NC}"
            else
                echo -e "${YELLOW}⊘ Skipping task $TASK_ID (deferred)${NC}"
            fi
        done
    fi
fi

# Final summary
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           FEATURE PLANNING COMPLETE                          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Session:   $SESSION_ID"
echo "Directory: $FEATURE_DIR/"
echo "Executed:  $TASKS_TO_EXECUTE"
[[ -n "$TASKS_TO_DEFER" ]] && echo "Deferred:  $(echo "$TASKS_TO_DEFER" | wc -l) tasks"
[[ -f "$FEATURE_DIR/DEFERRED_ISSUE.txt" ]] && echo "Issue:     $(cat "$FEATURE_DIR/DEFERRED_ISSUE.txt")"
echo ""
echo -e "${GREEN}Logged to .ai/ledger/LEDGER.md${NC}"

log_to_ledger "COMPLETED" "Executed: $TASKS_TO_EXECUTE, Deferred: $(echo "$TASKS_TO_DEFER" | wc -l) tasks"
